version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Adm_passwd1!"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        volumes:
            - ./:/host
